---
apiVersion: v1
kind: Template
name: addrewTrex-service-routes 
metadata:
  name: route

objects:

- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: addrewTrex-service
    labels:
      app: addrewTrex-service
  spec:
#    The cluster should assign a suitable host. If using CRC, it may be necessary to define one manually:
#    host: addrewTrex-service.apps-crc.testing
    to:
      kind: Service
      name: addrewTrex-service
    tls:
      termination: reencrypt
      insecureEdgeTerminationPolicy: Redirect
